### PR TITLE
Tackle-196 landscape report

### PR DESCRIPTION
**Pull request by jonathanvila**
Issue : https://github.com/konveyor/tackle-pathfinder/issues/66

### Features covered
* New endpoint "landscape" that will answer with a List of assessmentIds + assessment risk based on the answers
* Only considers assessments Complete

### Unit , Integration and End2End Tests cases covered
* Unit Test ( AssessmentSvcTest.java )
  * given_AssessmentWithNoRedAnswersSeveralAmber_When_landscape_Then_ResultIsAMBER
  * given_AssessmentWithNoRedAnswersFewAmber_When_landscape_Then_ResultIsGREEN
  * given_AssessmentWithRedAnswers_When_landscape_Then_ResultIsRED

* Integration Test ( AssessmentsResourceTest.java )
  * given_ApplicationsAssessed_When_LandscapeRequested_Then_ExpectedJSONIsReturned

* End2End Test on minikube with native image ( check_api.sh )
  * Tests 15

### Pre steps Minikube: 
1. Install minikube : https://minikube.sigs.k8s.io/docs/start/
1. Start minikube : minikube start --kubernetes-version=v1.20.2 --cpus 4 --memory 12000
1. Enable ingress addons : minikube addons enable ingress
1. Create tackle namespace
```Shell
kubectl create namespace tackle
``` 
1. Deploy tackle ( to have the keycloak instance running ) on your K8s cluster
```Shell
$ kubectl apply -f  https://raw.githubusercontent.com/konveyor/tackle/main/kubernetes/kubernetes-tackle.yaml -n tackle
```
5. Edit the Ingress object to allow direct request to Pathfinder API
```Shell
$ kubectl edit ingress tackle -n tackle
```
Add this below `paths:`
```Yaml
     - backend:
          service:
            name: tackle-pathfinder
            port:
              number: 8080 
        path: /pathfinder
        pathType: ImplementationSpecific
```
6. Build and push 
```Shell
$ ./mvnw -U -B package -Dquarkus.container-image.push=true -Dquarkus.container-image.group={your quay user} -Dquarkus.container-image.registry=quay.io -Dquarkus.container-image.username={your quay user} -Dquarkus.container-image.password={your quay pwd} -Pnative
```
7. Change the image in the deployment tackle-pathfinder to be the one you have pushed
8. Rollout to update the image
```Shell
$ kubectl rollout restart deployment tackle-pathfinder -n tackle
```

### Test case with Minikube : Do the full API test
```Shell
$ .github/scripts/check_api.sh
```
> Expect 
```Shell
+++++ API CHECK SUCCESSFUL ++++++
```

### Pre steps non containerised local test:
1. run keycloak
```Shell
podman run -it --name keycloak --rm \     
            -e KEYCLOAK_USER=admin -e KEYCLOAK_PASSWORD=admin -e KEYCLOAK_IMPORT=/tmp/keycloak/quarkus-realm.json \
            -e DB_VENDOR=h2 -p 8180:8080 -p 8543:8443 -v ./src/main/resources/keycloak:/tmp/keycloak:Z \
            jboss/keycloak:12.0.2
```
1. run postgresql
```Shell
podman run -it \                          
            --name postgres-pathfinder -e POSTGRES_USER=pathfinder \                                               
            -e POSTGRES_PASSWORD=pathfinder -e POSTGRES_DB=pathfinder_db \                              
            -p 5433:5432 postgres:10.6
```
1. run application
```Shell
./mvnw quarkus:dev
```
 
### Test case with local non containerised : Do the full API test
```Shell
$ .github/scripts/check_api.sh localhost:8085 localhost:8180
```
> Expect 
```Shell
+++++ API CHECK SUCCESSFUL ++++++
```

### CODE REVIEW

**Review by carlosthe19916 — CHANGES_REQUESTED** [review]
Thanks for this PR @jonathanvila . Here are my first thought about this PR.

## FYI: The landscape report should have 4 charts

- Low risk
- Medium risk
- High risk
- Unassesed apps

The last element "unassesed" has been discussed with @PhilipCattanach and even though it doesn't appear in the mockups we need to add it.

pasted image 0

It seems the current response is not enough for creating the last donut chart "unassessed".

## Endpoint response
The current endpoint `GET /assessments/landscape` is returning an array with the list of assessments and a risk associated with it: `UNKNOWN, RED, AMBER, GREEN`.

What does the `UNKNOWN` mean for the landscape report? It is not clear to me what will the UI do with this value. Maybe just ignore it?

## Where the logic for creating the landscape report should be located?
The endpoint `GET /assessments/landscape` is returning an array like:

```javascript
[
  {"assessmentId": 1, risk: "UNKNOWN"},
  {"assessmentId": 2, risk: "RED"},
  {"assessmentId": 3, risk: "GREEN"},
]
```

The array above will need to be processed and converted to some object like:
```javascript
{
   "low": 1,
   "medium": 0,
   "high": 1,
   "unassessed": 10
}
```
I think the current array should be converted to the object above in the backend rather than in the UI; otherwise, the UI will contain business logic that can not be shared through the APIs. When I mention the business logic I mean:
- What to do if the risk of an app is "UNKNOWN"? whatever is the decision should be written in the backend.

In general, if the endpoint is returning an array rather than the object needed for creating the landscape report then perhaps the endpoint shouldn't be called `/assessments/landscape` but just `/assessments/assessment-risks` because the response is not creating the data for the landscape.

**Comment by carlosthe19916** [comment]
Adding some notes after an internal chat with @jonathanvila  :
- The endpoint `GET /assessments/landscape` will NEVER return a risk whose value is UNKNOWN even if the enum used in the model includes it.
- The "unassesed" application will need to be calculated in the UI rather than the backend: `the number of unasseed application is equal to the total number of applications sent to the endpoint minus the length of the response of the current endpoint` => `totalAppsRequestedInUI - response.length`

**Comment by carlosthe19916** [comment]
@jonathanvila I just want to clarify/summarize all my previous comments:
- **About the 4th donut chart "Unassesed":** This is something the UI can do with the current data the backend is providing => `this PR doesn't need extra action on this topic`.
- **About risk `UNKNOWN`**: The endpoint GET /assessments/landscape will NEVER return a risk whose value is UNKNOWN even if the enum used in the model includes it => `this PR doesn't need extra action on this topic`.
- **About whether or not the landscape totals should be calculated in the backend or in the UI**: The current response of the backend is enough for the UI to create the donut charts. However, I think there is still a minor decision we need to make in this topic. I have 2 options we can choose:

1. Option 1: Currently the backend is returning an array. Can the response return an object containing the total values?. E.g.
```json
{
   "low": 1,
   "medium": 0,
   "high": 1
}
```

2. Option 2: Let's keep the endpoint as it is but change the name of the endpoint from `/assessments/landscape` to something like `/assessments/assessment-risks` (the name is up to you) since the endpoint itself is not creating the Landscape but providing data that will be processed/converted to the landscape report. If you ask me, I would go for this option but I'd like to know your opinion.

- **About the Rest endpoint GET**: As discussed in the internal meetings, changing the verb `GET` to `POST` is something we can do in order to reduce the risk of having a big URL calling the endpoint.

**Comment by jonathanvila** [comment]
@carlosthe19916 : 
1. Calculation : I agree with Option 2. Endpoint = /assessments/assessment-risks
2. Verb, changing to POST + body

**Comment by carlosthe19916** [comment]
Thanks @jonathanvila, this PR looks good to me.

**Pull request merged**
